{% set name = "telnetlib3" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jquast/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 861edc8eddb449e43efef55d51adfd30badebe017b0dac217757a8707a650c0c

build:
  entry_points:
    - telnetlib3-server = telnetlib3.server:main
    - telnetlib3-client = telnetlib3.client:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - telnetlib3
  commands:
    - pip check
    - telnetlib3-server --help
    - telnetlib3-client --help
  requires:
    - pip

about:
  home: http://telnetlib3.rtfd.org/
  summary: Python 3 asyncio Telnet server and client Protocol library
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - atrawog
