schema_version: 1

context:
  name: telnetlib3
  version: "2.6.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/telnetlib3-${{ version }}.tar.gz
  sha256: 6b365973df176ac1ddb823c98c99bb02f3a7540f7b94f22378651998e05754be

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - telnetlib3-server = telnetlib3.server:main
      - telnetlib3-client = telnetlib3.client:main
      - telnetlib3-fingerprint-server = telnetlib3.fingerprinting:fingerprint_server_main
      - telnetlib3-fingerprint = telnetlib3.client:fingerprint_main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - wcwidth >=0.6.0

tests:
  - python:
      imports:
        - telnetlib3
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.*
  - script:
      - telnetlib3-server --help
      - telnetlib3-client --help
      - telnetlib3-fingerprint-server --help
      - telnetlib3-fingerprint --help
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  summary: Python 3 asyncio Telnet server and client Protocol library
  license: BSD-3-Clause AND Python-2.0
  license_file: LICENSE.txt
  homepage: http://telnetlib3.rtfd.org/
  repository: https://github.com/jquast/telnetlib3

extra:
  recipe-maintainers:
    - atrawog
    - beenje
