schema_version: 1

context:
  name: telnetlib3
  version: 1.0.4

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/jquast/${{ name }}/archive/refs/tags/${{ version }}.tar.gz
  sha256: f911a81b9e6607fd8516ce3f40c9ef1a43b6b290b1f21b15237a83a1be6e4a61

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - telnetlib3-server = telnetlib3.server:main
      - telnetlib3-client = telnetlib3.client:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

tests:
  - python:
      imports:
        - telnetlib3
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
    script:
      - telnetlib3-server --help
      - telnetlib3-client --help

about:
  summary: Python 3 asyncio Telnet server and client Protocol library
  license: BSD-3-Clause
  license_file: LICENSE.txt
  homepage: http://telnetlib3.rtfd.org/

extra:
  recipe-maintainers:
    - atrawog
