schema_version: 1

context:
  name: telnetlib3
  version: "2.6.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/telnetlib3-${{ version }}.tar.gz
  sha256: c231e790c626f5b6927a4a85e79bce18cde994c9424254d2193582b430972164

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - telnetlib3-server = telnetlib3.server:main
      - telnetlib3-client = telnetlib3.client:main
      - telnetlib3-fingerprint-server = telnetlib3.fingerprinting:fingerprint_server_main
      - telnetlib3-fingerprint = telnetlib3.client:fingerprint_main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - wcwidth >=0.2.13

tests:
  - python:
      imports:
        - telnetlib3
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.*
  - script:
      - telnetlib3-server --help
      - telnetlib3-client --help
      - telnetlib3-fingerprint-server --help
      - telnetlib3-fingerprint --help
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  summary: Python 3 asyncio Telnet server and client Protocol library
  license: BSD-3-Clause AND Python-2.0
  license_file: LICENSE.txt
  homepage: http://telnetlib3.rtfd.org/
  repository: https://github.com/jquast/telnetlib3

extra:
  recipe-maintainers:
    - atrawog
    - beenje
